### ISSUE TITLE
Add TS1 as an example

### ISSUE THREAD

**Issue by K20shores** [NCAR/music-box-interactive-client#319]
Depends on [the TS1 issue](https://github.com/NCAR/music-box-interactive-api/issues/420) on the server being done. But, add TS1 as an example 

**Acceptance criteria**
- TS1 can be loaded from the server and a simulation can be run with the results viewed

**Ideas**
- Add TS1 as an example in `src/components/GettingStarted/Examples.jsx`
  - To do so, a new entry in `src/redux/utils.js` for TS1 will be necessary

**Comment by carl-drews** [comment]
Here is the current python error:
```
INFO:acom_music_box.music_box_main:Working directory = C:\2024\MusicBox\music-box-interactive-api\interactive\api\static\examples
INFO:acom_music_box.music_box_main:Command line = {'key_value_pairs': None, 'configFile': 'TS1\\my_config.json', 'outputDir': 'TS1'}
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\drews\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\music_box.exe\__main__.py", line 7, in <module>
  File "C:\Users\drews\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\acom_music_box\music_box_main.py", line 79, in main
    myBox.readConditionsFromJson(musicBoxConfigFile)
  File "C:\Users\drews\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\acom_music_box\music_box.py", line 662, in readConditionsFromJson
    self.initial_conditions = Conditions.from_config_JSON(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drews\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\acom_music_box\music_box_conditions.py", line 177, in from_config_JSON
    if not any(rate.reaction.name ==
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drews\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\acom_music_box\music_box_conditions.py", line 177, in <genexpr>
    if not any(rate.reaction.name ==
               ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
```

This error occurs because initial_conditions.csv is not correct. Try leaving out those initial conditions.

**Comment by carl-drews** [comment]
Now we have some missing entries for Argon. I will dig into those.

```
INFO:acom_music_box.music_box_main:CAMP config = TS1\camp_data/config.json
INFO:acom_music_box.music_box_main:myBox.solver = <musica.micm object at 0x0000026236B388F0>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\drews\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\music_box.exe\__main__.py", line 7, in <module>
  File "C:\Users\drews\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\acom_music_box\music_box_main.py", line 89, in main
    mySolution = myBox.solve(os.path.join(musicBoxOutputDir, "mySolution.csv"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drews\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\acom_music_box\music_box.py", line 491, in solve
    ordered_concentrations = self.order_species_concentrations(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drews\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\acom_music_box\music_box.py", line 736, in order_species_concentrations
    ordered_concentrations[species_constant_ordering[key]] = value
                           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 'Ar'
```

**Comment by K20shores** [comment]
@carl-drews that's likely from initial spedies concentrations in my_config.json. I'm betting TS1 doesn't contain argon, strangely enough
